const COMMON_STORY_ARGS = {
  disabled: {
    control: { type: 'boolean' },
  },
  required: {
    control: { type: 'boolean' },
  },
  checked: {
    control: { type: 'boolean' },
  },
  readOnly: {
    control: { type: 'boolean' },
  },
  bootstrapColor: {
    control: { type: 'select' },
    options: [
      'primary',
      'secondary',
      'success',
      'info',
      'warning',
      'danger',
      'light',
      'dark',
      'accent-primary',
      'accent-secondary',
    ],
  },
  // TODO: Use bootstrap color names. Issue #202.
  numberColor: {
    control: { type: 'select' },
    options: [
      'color-1',
      'color-2',
      'color-3',
      'color-4',
      'color-5',
      'color-light',
      'color-dark',
    ],
  },
  order: {
    control: { type: 'select' },
    options: ['left', 'right'],
  },
  // TODO: Make the following two size attr names/values
  // consistent. Issue #202.
  size: {
    control: { type: 'select' },
    options: ['sm', 'md', 'lg', 'xl'],
  },
  longSize: {
    control: { type: 'select' },
    options: ['small', 'medium', 'large', 'x-large'],
  },
  icon: {
    control: { type: 'select' },
    options: [
      'bicycle',
      'bounding-box',
      'bounding-box-circle',
      'building',
      'building-fill',
      'buildings',
      'buildings-fill',
      'bus-front',
      'bus-front-fill',
      'calendar',
      'calendar-fill',
      'calendar-date',
      'calendar-date-fill',
      'cash',
      'check-circle',
      'check-circle-fill',
      'chevron-right',
      'chevron-right-circle',
      'chevron-right-circle-fill',
      'chevron-left',
      'chevron-left-circle',
      'chevron-left-circle-fill',
      'chevron-up',
      'chevron-up-circle',
      'chevron-up-circle-fill',
      'chevron-down',
      'chevron-down-circle',
      'chevron-down-circle-fill',
      'currency-dollar',
      'exclamation-circle',
      'exclamation-circle-fill',
      'exclamation-triangle',
      'file-earmark',
      'funnel',
      'funnel-fill',
      'house',
      'house-fill',
      'list-task',
      'newspaper',
      'no-parking',
      'no-parking-fill',
      'journals',
      'p-circle',
      'p-circle-fill',
      'toilet',
      'universal-access',
      'universal-access-circle',
      'wifi',
      'wifi-off',
    ].sort(),
  },
};

export { COMMON_STORY_ARGS };
